/*
 *
 * Copyright (c) 2022 The Ontario Institute for Cancer Research. All rights reserved
 *
 *  This program and the accompanying materials are made available under the terms of
 *  the GNU Affero General Public License v3.0. You should have received a copy of the
 *  GNU Affero General Public License along with this program.
 *   If not, see <http://www.gnu.org/licenses/>.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY
 *  EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 *  OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT
 *  SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 *  INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
 *  TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
 *  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER
 *  IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 *  ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 */

import getNextConfig from 'next/config';

type Config = {
	NEXT_PUBLIC_ARRANGER_ADMIN_UI: string;
	NEXT_PUBLIC_ARRANGER_API: string;
	NEXT_PUBLIC_ARRANGER_DOCUMENT_TYPE: string;
	NEXT_PUBLIC_ARRANGER_INDEX: string;
	NEXT_PUBLIC_ARRANGER_CARDINALITY_PRECISION_THRESHOLD: number;
	NEXT_PUBLIC_ARRANGER_MANIFEST_COLUMNS: string;
	NEXT_PUBLIC_ARRANGER_MAX_BUCKET_COUNTS: number;
	NEXT_PUBLIC_BASE_PATH: string;
	NEXT_PUBLIC_ADMIN_EMAIL: string;
	NEXT_PUBLIC_SYSTEM_ALERTS: string;
	NEXT_PUBLIC_APP_VERSION: string;
	NEXT_PUBLIC_APP_COMMIT: string;
	NEXT_PUBLIC_DEBUG: boolean;
	NEXT_PUBLIC_ENABLE_DOWNLOADS: boolean;
	NEXT_PUBLIC_ENABLE_LOGIN: boolean;
	NEXT_PUBLIC_ENABLE_REGISTRATION: boolean;
};

export const getConfig = (): Config => {
	const publicConfig: { [k: string]: string } = getNextConfig()?.publicRuntimeConfig || {};

	return {
		NEXT_PUBLIC_ARRANGER_ADMIN_UI: publicConfig.NEXT_PUBLIC_ARRANGER_ADMIN_UI,
		NEXT_PUBLIC_ARRANGER_API: publicConfig.NEXT_PUBLIC_ARRANGER_API || 'http://localhost:5050',
		NEXT_PUBLIC_ARRANGER_DOCUMENT_TYPE: publicConfig.NEXT_PUBLIC_ARRANGER_DOCUMENT_TYPE || '',
		NEXT_PUBLIC_ARRANGER_INDEX: publicConfig.NEXT_PUBLIC_ARRANGER_INDEX || '',
		NEXT_PUBLIC_ARRANGER_CARDINALITY_PRECISION_THRESHOLD:
			Number(publicConfig.NEXT_PUBLIC_ARRANGER_CARDINALITY_PRECISION_THRESHOLD) || 3000,
		NEXT_PUBLIC_ARRANGER_MANIFEST_COLUMNS: publicConfig.NEXT_PUBLIC_ARRANGER_MANIFEST_COLUMNS || '',
		NEXT_PUBLIC_ARRANGER_MAX_BUCKET_COUNTS:
			Number(publicConfig.NEXT_PUBLIC_ARRANGER_MAX_BUCKET_COUNTS) || 1000,
		NEXT_PUBLIC_BASE_PATH: publicConfig.NEXT_PUBLIC_BASE_PATH || '',
		NEXT_PUBLIC_ADMIN_EMAIL: publicConfig.NEXT_PUBLIC_ADMIN_EMAIL,
		NEXT_PUBLIC_SYSTEM_ALERTS: publicConfig.NEXT_PUBLIC_SYSTEM_ALERTS || '[]',
		NEXT_PUBLIC_APP_VERSION: publicConfig.NEXT_PUBLIC_APP_VERSION || '',
		NEXT_PUBLIC_APP_COMMIT: publicConfig.NEXT_PUBLIC_APP_COMMIT || '',
		// Optional features/functionalities
		NEXT_PUBLIC_DEBUG: (publicConfig.NEXT_PUBLIC_DEBUG || '').toLowerCase() === 'true',
		NEXT_PUBLIC_ENABLE_DOWNLOADS:
			(publicConfig.NEXT_PUBLIC_ENABLE_DOWNLOADS || '').toLowerCase() === 'true',
		NEXT_PUBLIC_ENABLE_LOGIN:
			(publicConfig.NEXT_PUBLIC_ENABLE_LOGIN || '').toLowerCase() === 'true',
		NEXT_PUBLIC_ENABLE_REGISTRATION:
			(publicConfig.NEXT_PUBLIC_ENABLE_REGISTRATION || '').toLowerCase() === 'true',
	};
};
