/*
 *
 * Copyright (c) 2024 The Ontario Institute for Cancer Research. All rights reserved
 *
 *  This program and the accompanying materials are made available under the terms of
 *  the GNU Affero General Public License v3.0. You should have received a copy of the
 *  GNU Affero General Public License along with this program.
 *  If not, see <http://www.gnu.org/licenses/>.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY
 *  EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 *  OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT
 *  SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 *  INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
 *  TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
 *  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER
 *  IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 *  ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 */

import { ReactElement } from 'react';
import { css, useTheme } from '@emotion/react';

import defaultTheme from '../../theme';
import ArticleComponent from './ArticleComponent';
import NoteBox from './notebox';

import { EMAIL } from '@/global/utils/constants';

const Content = ({ activeId }: { activeId: string }): ReactElement => {
	const theme: typeof defaultTheme = useTheme();

	return (
		<main
			css={css`
				width: 100%;
				background-color: ${theme.colors.white};
				padding-bottom: ${theme.dimensions.footer.height}px;
				display: flex;
				justify-content: center;
				align-items: center;
			`}
		>
			<div
				css={css`
					width: 100%;
					max-width: 1200px;
					padding: 0 48px;
					box-sizing: border-box;
				`}
			>
				{/* Data */}
				{activeId === 'data' && (
					<div>
						<ArticleComponent
							title="Dataset Description"
							text="This demo contains a mock dataset that simulates a real-world scenario where multiple cancer research groups are gathering and sharing their cancer genomics data. The data model organizes genomes in tumour-normal pairings, a typical setup in genomic studies where one sample is a tumour tissue and the other is a matched healthy tissue. This arrangement allows the researchers to compare genetic variations between the two types of tissues, providing insights into disease mechanisms and potential therapeutic targets."
						/>
						<ArticleComponent title="Data Curation Process" text="">
							The schema was designed to support clinical, workflow, and experimental metadata. The
							clinical data schema was based on the{' '}
							<a href="https://docs.icgc-argo.org/dictionary">ICGC-ARGO dictionary</a>. Workflow and
							experimental metadata schemas were based on the{' '}
							<a href="https://github.com/icgc-argo/argo-metadata-schemas/tree/master/schemas">
								ICGC-ARGO metadata schemas
							</a>
							, specifically focusing on sequencing alignments and variant calls. Metadata was
							randomly generated following these schemas and manually curated to ensure a degree of
							believability. Variant calls and sequencing files were generated by a custom script in
							Python, based on genome build Hg38 Chr1:100000-200000, following the specifications
							outlined in the <a href="https://samtools.github.io/hts-specs/CRAMv3.pdf">CRAM v3</a>,{' '}
							<a href="https://samtools.github.io/hts-specs/VCFv4.4.pdf">VCF v4.4</a>, and{' '}
							<a href="https://samtools.github.io/hts-specs/VCFv4.4.pdf">SAM v1</a> specifications.
						</ArticleComponent>

						<ArticleComponent
							title="Use Restrictions"
							text="This dataset is intended for demo purposes only."
						/>
						<NoteBox title="Contact Information">
							If you have inquiries about this dataset, please contact us at{' '}
							<a href={EMAIL}>contact@overture.bio</a>. We welcome feedback and suggestions for
							improving the quality and usability of our datasets.
						</NoteBox>
					</div>
				)}
				{/* Terms */}
				{activeId === 'terms' && (
					<div>
						<ArticleComponent title="1 Terms & Conditions of Use of Site" text=" ">
							<p>
								This website (the “Site”) is provided to you subject to your agreement to and
								compliance with the terms and conditions of use set forth below (the “Terms and
								Conditions”). By visiting or otherwise using this Site, including without
								limitation, accessing, using, and/or downloading messages, information, data, text,
								video, software or images, or other content from this Site (collectively the
								“Content”), or sending messages, information, data, text, video, software or images,
								or other Content to the Site, you agree on your own behalf, and on behalf of any
								entity on whose behalf you may act, to accept and abide by the Terms and Conditions
								for each use of and each visit to this Site. If you do not agree to abide by these
								Terms and Conditions, please do not use this Site.
							</p>
							<p>
								OICR has the right, in its sole discretion, to add to, remove, modify or otherwise
								change the Terms and Conditions, in whole or in part, at any time. Please check the
								Terms and Conditions frequently by checking the date of “Last Updated” at the top of
								this document to see if there have been any changes that may affect your decision on
								whether or not to use the Site. If any term, condition or any change thereto is not
								acceptable to you, you must discontinue your use of this Site immediately. Your
								continued use of this Site after any such changes are posted will constitute
								acceptance of those changes. These Terms and Conditions apply exclusively to your
								use of this Site and do not alter the terms or conditions of any other agreement you
								may have with OICR.
							</p>
							<p>
								OICR may, at any time without notice or liability, and for any reason whatsoever,
								terminate, change, suspend or discontinue any aspect of this Site, including (i)
								changing the availability of, restricting access to, or imposing limits on any or
								all features or services on, or links to, the Site; (ii) adding, removing or
								changing any fees or charges for use of the Site or any features thereof; and (iii)
								removing, adding, modifying or otherwise changing any Content on this Site. OICR
								reserves the right, in its sole discretion, to correct any errors or omissions in
								any portion of this Site at any time without notice, but confirms that it has no
								duty to do so.
							</p>
						</ArticleComponent>
						<ArticleComponent title="2 Website Privacy Statement" text=" ">
							<p>
								The Website Privacy Statement applies to your use of this website. Please ensure you
								have read and agree with the Website Privacy Statement. By visiting and using this
								Site, you are consenting to the collection, use and disclosure of your Personal
								Information while visiting the Site.
							</p>
						</ArticleComponent>
						<ArticleComponent title="3 Proprietary Rights" text=" ">
							<p>
								The Site Content is protected by copyright, trademark, and other applicable
								intellectual property and proprietary rights laws, and is owned, controlled, and/or
								licensed by OICR and/or its affiliates, or other third-party content providers. Any
								unauthorized copying, redistribution, reproduction or modification of the Content by
								any person may be a violation of trademark and/or copyright laws and could subject
								such person to legal action. Any use of any Content, in whole or in part, without
								prior written authorization of OICR is strictly prohibited.
							</p>
							<p>
								You agree to comply with all applicable intellectual property and proprietary rights
								laws in your use of this Site and to prevent any unauthorized copying of the
								Content.
							</p>
						</ArticleComponent>
						<ArticleComponent title="4 Restrictions on Site Use" text=" ">
							<p>
								Subject to the Terms and Conditions, you are granted a non-exclusive,
								non-transferable, non-sub-licensable, revocable, limited license to display on your
								computer, print and download and use the content of this Site for informational
								purposes only and solely for your own non-commercial, personal or internal company
								use provided you retain all copyright and other proprietary notices. No other use is
								permitted.
							</p>
							<p>Prohibited uses include, without limitation:</p>
							<ul>
								<li className="bullet">reselling any Content;</li>
								<li className="bullet">
									including any Content in or with any product that you create or distribute unless
									the copyright attribution accompanies such Content;
								</li>
								<li className="bullet">copying any Content onto your own or any other website;</li>
								<li className="bullet">
									removing any proprietary notices or labels on this Site or the Content provided on
									this Site;
								</li>
								<li className="bullet">
									plagiarizing the Content on this site or otherwise violating or infringing the
									Proprietary Rights of OICR or any third party; or
								</li>
								<li className="bullet">
									using this Site in any manner that could damage, disable, overburden, impair,
									interfere with the security of, negatively affect the functioning of, or otherwise
									abuse, this Site or any services, system resources, accounts, servers, networks,
									or affiliated or linked sites, connected to or accessible through this Site
									(including without limitation uploading, posting or otherwise transmitting on this
									Site computer viruses, Trojan horses, worms or other files or computer programs
									which are potentially harmful, disruptive or destructive or that may impose an
									unreasonable or disproportionately large load on this Site’s infrastructure).
								</li>
							</ul>
							<p>
								In addition, you agree that you are solely responsible for actions and
								communications undertaken or transmitted in the course of your use of this Site, and
								that you will comply with all laws that apply or may apply to your use of or
								activities on this Site or in respect of the Content. OICR will investigate
								occurrences which may involve violations of such laws, and may involve, and
								co-operate with, law enforcement authorities in prosecuting users who are involved
								in such violations. OICR reserves the right at all times to disclose any information
								regarding your usage of the Site as necessary to satisfy any law, regulation or
								governmental request.
							</p>
						</ArticleComponent>
						<ArticleComponent title="5 Links to Third Party Websites" text=" ">
							<p>
								Certain links on this Site may take you to other websites. All such other websites
								are independent from this Site and OICR provides these links as a convenience only.
							</p>
							<p>
								OICR has no control over, and is not responsible for, the content of any such linked
								pages. OICR makes no representation or warranty regarding, and does not endorse, any
								linked websites, the information appearing thereon or any of the products or
								services described. If you follow these links, you will leave this Site. If you
								decide to visit any linked site, you do so at your own risk and it is your
								responsibility to take all protective measures to guard against viruses and other
								destructive elements. The terms of use and privacy policies applicable to such
								websites may be different than those applicable to this website. OICR may terminate
								a link at any time.
							</p>
							<p>
								OICR welcomes links to this Site. However, you agree that if you want to link to
								this Site, your website shall not:
							</p>
							<ul>
								<li className="bullet">
									create frames around any part of this Site or use other techniques that alter the
									visual presentation of this Site;
								</li>
								<li className="bullet">
									imply that OICR is endorsing you or any other person, or your or such other
									person’s products or services;
								</li>
								<li className="bullet">
									imply an affiliation between you or any other person, or your or such other
									person’s products or services, and OICR without the prior written consent of OICR;
								</li>
								<li className="bullet">
									misrepresent your relationship or that of any other person with OICR or present
									false, misleading or otherwise damaging information or impressions about OICR or
									any of its products or services; or
								</li>
								<li className="bullet">
									contain materials that may be interpreted as distasteful, harmful, offensive,
									infringing or inaccurate.
								</li>
							</ul>
							<p>
								You acknowledge and agree that OICR reserves the right to request, at any time and
								in its sole discretion, that you remove all links or any particular link to the Site
								or any other OICR website or to a page of the Site or any other OICR website.
							</p>
						</ArticleComponent>
						<ArticleComponent title="6 Disclaimers" text=" ">
							<p>
								This Site is provided on an “as-is, as available” basis. While OICR believes the
								Content on this Site to be correct, OICR makes no representations or warranties
								regarding the accuracy, completeness or currency of any Content displayed on this
								Site.
							</p>
							<p>
								This Site is designed for informational purposes and for event registration only.
								The Site does not provide medical advice or professional services, and should not be
								relied upon as such. The information provided on this Site is not intended as a
								substitute for medical professional help or advice, but is to be used only as an aid
								in understanding current medical knowledge. A physician should always be consulted
								for any health problem or question, or medical condition. Use of or reliance on the
								information displayed on this Site is at your own risk.
							</p>
						</ArticleComponent>
						<ArticleComponent title="7 Limitations of Liability" text=" ">
							<p>
								TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL OICR AND ITS RESPECTIVE
								DIRECTORS, OFFICERS, MEMBERS, AGENTS, EMPLOYEES, REPRESENTATIVES AND LICENSORS
								(COLLECTIVELY THE “OICR PARTIES”) BE LIABLE FOR ANY DIRECT, INDIRECT, SPECIAL,
								INCIDENTAL OR CONSEQUENTIAL DAMAGES WHATSOEVER (INCLUDING, WITHOUT LIMITATION,
								DAMAGES FOR LOSS OF PROFITS, FAILURE TO REALIZE EXPECTED SAVINGS, INTERRUPTION OF
								ACTIVITIES, OR ANY OTHER PECUNIARY OR ECONOMIC LOSS) ARISING OUT OF THE USE OF OR
								INABILITY TO USE THIS SITE, EVEN IF ANY OF THE PARTIES HAVE BEEN ADVISED OF THE
								POSSIBILITY OF SUCH DAMAGES. IN ANY EVENT, THE PARTIES’ TOTAL LIABILITY TO YOU FOR
								ALL DAMAGES, LOSSES AND CAUSES OF ACTION, WHETHER IN CONTRACT OR TORT (INCLUDING
								NEGLIGENCE) OR OTHERWISE, SHALL BE LIMITED TO THE AMOUNT ACTUALLY PAID BY YOU TO
								ACCESS THIS SITE, IF ANY. IN NO EVENT SHALL ANY OICR PARTY BE LIABLE FOR DAMAGES OR
								LOSSES OF ANY KIND ARISING FROM THE USE OF ANY HYPERLINKED WEBSITE.
							</p>
							<p>
								BY USING THE CONTENT, YOU AGREE TO INDEMNIFY OICR AND ITS CONTENT PROVIDERS FROM ANY
								AND ALL LIABILITY, LOSS, INJURY, DAMAGES, COSTS AND EXPENSES (INCLUDING LEGAL FEES
								AND EXPENSES) ARISING FROM YOUR USE OF THE CONTENT.
							</p>
						</ArticleComponent>
						<ArticleComponent title="8 General" text=" ">
							<p>
								These Terms and Conditions shall be governed by and construed in accordance with the
								laws in force in the province of Ontario and the federal laws of Canada applicable
								therein, and any dispute arising hereunder shall be resolved exclusively by the
								courts in the province of Ontario.
							</p>
						</ArticleComponent>
					</div>
				)}
				{/* Privacy */}
				{activeId === 'privacy' && (
					<div>
						<ArticleComponent
							title="Application"
							text="
          This Privacy Statement applies to the Overture Demo Portal. Information collected through this
          website falls into two categories: aggregate information and personal information.
        "
						></ArticleComponent>
						<ArticleComponent title="Collection and Use" text="">
							<p>
								Aggregate information is information from which individual user identities or
								characteristics have been removed. When a user accesses the Overture website,
								aggregate information is collected automatically in order to better understand
								website traffic patterns (e.g., total number of visitors, most visited sections,
								peak traffic times). None of this information is personally identifiable.
							</p>
							<p>
								Personal information is any information about an identifiable individual. When we
								collect personal information about you through the website, we do so only if you
								consent to provide it to us. Specifically, If you send us an inquiry through our
								website, we only collect your email address in order to respond to you.
							</p>
							<p>
								OICR will not disclose your personal information other than in the following two
								situations:
							</p>
							<ol>
								<li>
									<p>
										Aggregate information is information from which individual user identities or
										characteristics have been removed. When a user accesses the OICR website,
										aggregate information is collected automatically in order to better understand
										website traffic patterns (e.g., total number of visitors, most visited sections,
										peak traffic times). None of this information is personally identifiable.
									</p>
								</li>
								<li>
									<p>
										Personal information is any information about an identifiable individual. When
										we collect personal information about you through the website, we do so only if
										you consent to provide it to us. Specifically, If you send us an inquiry through
										our website, we only collect your email address in order to respond to you.
									</p>
								</li>
							</ol>
						</ArticleComponent>
						<ArticleComponent
							title="Disclosure"
							text="The Overture website may contain links to one or more third party websites. Please note
          that third party websites are not controlled by OICR, and this Privacy Statement does not
          apply in regard to any personal information that you provide to third party websites."
						/>
						<ArticleComponent title="Additional Information" text="">
							{' '}
							<p>
								If you would like to learn more about OICR’s commitment to protecting privacy,
								please see our{' '}
								<a href="https://oicr.on.ca/oicr-policies-and-procedures/">
									organizational Privacy Policy
								</a>
								.
							</p>
							<p>
								If you have any questions or concerns about privacy at OICR, please send a written
								request to:
							</p>
							<div className="bold"> Attn: Privacy Officer</div>
							<div>Ontario Institute for Cancer Research</div>
							<div>MaRS Centre, South Tower</div>
							<div>661 University Avenue, Suite 510</div>
							<div>Toronto, Ontario</div>
							<div>Canada M5G 0A3</div>
							<div>
								<span className="bold pr1">Email:</span>
								<a href="mailto:privacy@oicr.on.ca"> privacy@oicr.on.ca</a>
							</div>
						</ArticleComponent>
					</div>
				)}
			</div>
		</main>
	);
};

export default Content;
